status = error
name = MovieLensFeaturePipelineLog4j2
appender.console.type = Console
appender.console.name = stderr
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{ISO8601} %-5p %c{1}: %m%n
rootLogger.level = warn
rootLogger.appenderRef.stderr.ref = stderr
